name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: docker
    container:
      image: forge.ltfourrier.net/laurent/rust-node:latest
    steps:
      - uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    runs-on: docker
    container:
      image: forge.ltfourrier.net/laurent/rust-node:latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug Docker access
        run: |
          docker info

      - name: Run tests
        run: cargo test --workspace
